### ISSUE TITLE
The specified key 'address1_stateorprovince' does not exist in the ExpandoObject

### ISSUE THREAD

**Issue by pab74** [LinkeD365/MockarooDataMunger#8]
Hello, now i faced this problem when mapping postalcode o stateorprovince
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: **The specified key 'address1_stateorprovince' does not exist in the ExpandoObject.**
   at System.Dynamic.ExpandoObject.System.Collections.Generic.IDictionary<System.String,System.Object>.get_Item(String key)
   at LinkeD365.MockDataGen.MockDataGenCtl.<>c__DisplayClass29_0.<btnMockData_Click>b__1(BackgroundWorker w, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by LinkeD365** [comment]
Hey @pab74 I have fixed a couple of things around the display of fields and the save file, could you try version 1.202.8.7 and let me know if you can repro? If so, let me know the steps or a quick screen share?

**Comment by pab74** [comment]
Just updated to the latest version, but still have the problem
https://www.loom.com/share/7939ba8dbb1448f7a412e577be0dfee7

**Comment by LinkeD365** [comment]
Ok, thanks @pab74 will try & repro. Without the field it is fine?

**Comment by pab74** [comment]
yep, without that field is ok

Il giorno ven 28 ago 2020 alle ore 11:25 LinkeD365 <notifications@github.com>
ha scritto:

**Comment by LinkeD365** [comment]
Ok, worked it out. State (abbrev) has a lot of blanks, as the data from Mockaroo only populates for some countries. I need to fix the mock as it accepts a boolean for US only which I didn't realise, but need a little more time. For now, it should give you the right bits. 8.8 should be with you soon.

**Comment by pab74** [comment]
Thx!

Il ven 28 ago 2020, 12:33 LinkeD365 <notifications@github.com> ha scritto:
